# Site settings
baseurl = "https://example.org/"
themesDir = "themes"
languageCode = "en-us"
title = "/dev/ser (ou não?!)"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "spf13"

[params]
	name = "/dev/ser (ou não?!)"
	description = "Deve ser um ser dev."
	bio = "Deve ser um ser dev."
	# Enter optionally your twitter account
	#twitter = "Your Twitter account"
	enableRSS = false

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Rafael Santos é Engenheiro Físico (UFSCar) e Mestre em Ciências da Computação (USP). A paixão veio cedo: criou seu primeiro website pessoal em 1999, e trabalha com desenvolvimento web desde 2006."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    facebook = "https://www.facebook.com/rafaelpagliuca"
    github   = "https://www.github.com/rpagliuca"
