# Site settings
baseurl = "https://devser.com.br/"
themesDir = "themes"
languageCode = "pt-br"
title = "/dev/ser"
theme = "hugo-cactus-theme"
canonifyURLs = true
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-97834327-1"
# Disable comments by leaving disqusShortname empty
disqusShortname = "devser"
paginate = 1000

[markup.goldmark.renderer]
unsafe = true

[params]
	name = "Rafael Santos"
	bio = "Deve ser um ser dev"

	# Enter optionally your twitter account
	#twitter = "Your Twitter account"
	enableRSS = false

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = ["css/custom-styles.css"]
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Engenheiro Físico (UFSCar) e Mestre em Ciências da Computação (USP). A paixão veio de criança: criou seu primeiro website pessoal em 1999. Trabalha com desenvolvimento de software desde 2006."
	tweet = ""
	share = ""
	# 404 page
	title404 = "Ops... artigo não encontrado!"
	subtitle404 = "Este blog foi recentemente migrado de plataforma, e por isso alguns links deixaram de funcionar. Por favor, utilize a lista abaixo para acessar o artigo desejado."

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    facebook = "https://www.facebook.com/rafaelpagliuca"
    github   = "https://www.github.com/rpagliuca"
